config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registrations
  resources :gigs, except: [:show] do
    member do
      get 'duplicate'
    end
  end
  
  post 'band/edit' => 'gigs#edit_band'

  get 'settings' => 'gigs#settings'
  post 'settings' => 'gigs#post_settings'
  post 'settings/edit_status' => 'gigs#edit_status'
  post 'settings/edit_template' => 'gigs#edit_template'

  match 'dringende_massnahmen' => 'gigs#apply', :as => :dringende_massnahmen, :via => :get
  post 'apply' => 'gigs#post_apply'
  post 'jump' => 'gigs#post_jump'
  get 'show_mail/:id' => 'gigs#show_mail', as: "show_mail"
  get 'recreate_mail/:id' => 'gigs#recreate_mail', as: "recreate_mail"
  get 'remove_mail/:id' => 'gigs#remove_mail', as: "remove_mail"
  post 'edit_mail' => 'gigs#edit_mail', as: "edit_mail"
  get 'send_single_mail' => 'gigs#send_single_mail', as: "send_single_mail"

  post 'gigs/create_reminder'
  post 'gigs/create_email'

  get 'locations' => 'gigs#locations'
  post 'locations' => 'gigs#post_locations'
  post 'gigs/edit_location' => 'gigs#edit_location'
  get 'contacts' => 'gigs#contacts'
  post 'contacts' => 'gigs#post_contacts'
  post 'gigs/edit_contact' => 'gigs#edit_contact'

  
  get 'map' => 'gigs#map'

  get 'activities' => 'gigs#activities'
  post 'activities' => 'gigs#post_activities'

  root 'gigs#index'

end

app/models/gig.rb
class Gig < ActiveRecord::Base
	belongs_to :user
	has_many :status
	has_many :email
	has_many :reminder
	belongs_to :location

	validates :location_id, presence: true
	validates :name, presence: true
	validates :datetime, presence: true
	validates_format_of :datetime, :with => /(\d\d\d\d-\d\d-\d\d \d\d:\d\d)|(\d\d\d\d-\d\d-\d\d)/

	def short_text
		location ? "#{location.name} #{name}" : "(nicht zugeordnet)"
	end

	def short_location
		location ? (location.address + (contact ? "" : "<strong style='color:red'> (Kontakt fehlt)</strong>")) : "(unklar)"
	end

	def current_status
		if status and not status.empty?
			StatusValue.find(status.order(:created_at).last.status_value_id).text
		else
			nil
		end
	end

	def archived
		current_status == "archiviert"
	end

	def contact
		if location
			if location.contactlocation
				if location.contactlocation.first
					if location.contactlocation.first.contact
						c = location.contactlocation.first.contact
						return c
					end
				end
			end
		end

		nil
	end

	def datetimereadable
		if datetime
			datetime.strftime("%Y-%m-%d %H:%M")
		else
			""
		end
	end
	
	def contact_summary
		c = contact
		if c
			"#{c.name} (#{c.email})"
		else
			"(nicht zugeordnet)"
		end
	end






	def last_action_datetime
		if email and not email.empty?
			last_message_datetime = email.order(:transferred_at).reverse.first.transferred_at

			if last_message_datetime
				if status.last.updated_at > last_message_datetime
					return status.last.updated_at
				else
					return last_message_datetime
				end
			end
		end
		
		status.last.updated_at
	end

	def last_action
		Rails.datetime_relative(last_action_datetime)
	end

	def last_action_style
		Rails.datetime_relative_style(last_action_datetime)
	end

	def action_count
		email.count + status.count
	end

	def duplicate_for_next_year
	    copy = self.dup
	    if copy.location.festival
	      copy[:name] = (copy.name.to_i + 1).to_s
	      copy[:datetime] = copy.datetime + 1.year
	    end

	    copy.save

	    Status.create(gig_id: copy.id, status_value_id: StatusValue.find_by(text: "unbearbeitet").id)

	    return copy
	end

	def ensure_next_year
		if location.festival and not current_status == "archiviert"
			last = location.gig.sort_by { |x| x.datetime }.last

			if last.datetime < DateTime.now
				duplicate_for_next_year
				return 1
			end
		end
		return 0
	end





	def get_apply_email
		# es wird nil zurückgegeben, wenn für diesen Gig keine Bewerbung mehr abgeschickt werden muss

		apply_created_email_type = EmailType.find_by(text: "apply_created")
		apply_sent_email_type = EmailType.find_by(text: "apply_sent")
		manually_entered_type = EmailType.find_by(text: "manually_entered")
		raise "rake db:seed!" unless apply_created_email_type


		if location and contact
			return nil if gibt_es_schon_eine_abgesendete_bewerbungs_mail?

			template = Email.get_template
			apply_created_mails = Email.where(gig_id: id, email_type_id: apply_created_email_type.id)
			manually_entered_mails = Email.where(gig_id: id, email_type_id: manually_entered_type.id).order(:transferred_at)

			if apply_created_mails.count == 0
				if manually_entered_mails.count == 0

					# E-Mail erzeugen
					mail = Email.create(
						subject: replace_variables(template.subject), 
						text: replace_variables(template.text),
						email_type_id: apply_created_email_type.id,
						gig_id: id)

					unless mail
						raise "E-Mail konnte nicht erzeugt werden ... subject: #{replace_variables(template.subject)}; text: #{replace_variables(template.text)}; email_type_id: #{apply_created_email_type.id}"
					end

					return mail
				else
					# wenn es nur eine manuelle E-Mail gibt und sie schon übertragen wurde, passt alles
					if manually_entered_mails.count == 1
						if manually_entered_mails.first.transferred_at
							return nil
						else
							return manually_entered_mails.first
						end
					else
						# keine Unterscheidung an dieser Stelle. Wird schon passen, wenn mehr als eine manuelle E-Mail da ist
						return nil
					end
				end
			elsif apply_created_mails.count == 1
				# E-Mail wurde schon erzeugt
				m = apply_created_mails.first
				if m.transferred_at
					# falsch gekennzeichnet - wurde ja schon versendet
					m[:email_type_id] = apply_sent_email_type.id
					m.save

					return nil
				else
					return m
				end
			end
		end

		return nil
	end

	def gibt_es_schon_eine_abgesendete_bewerbungs_mail?
		apply_sent_email_type = EmailType.find_by(text: "apply_sent")

		return Email.where(gig_id: id, email_type_id: apply_sent_email_type.id).count > 0
	end

	def replace_variables(text)
		text = text.gsub(/\$contact-name\$/, contact.name)
		text = text.gsub(/\$location-name\$/, location.festival ? location.name + "-Festival" : location.name)
		text = text.gsub(/\$responsible\$/, User.find_by(id: user_id).name)
		text = text.gsub(/\$year\$/, datetime.year.to_s)
		text
	end









	# class methods
	def self.all_that_need_to_be_checked(how=nil)
		result = []

		all.each do |g|
			next if not g.current_status == "unbearbeitet" and not g.current_status == "zufrueh"

			mail = g.get_apply_email
			if mail
				c = g.contact

				if how == "via email"
					if c and not c.email.empty? and c.email.include? "@"
						result << g
					end
				elsif how == "via email"
					if c.email.empty? or not c.email.include? "@"
						result << g
					end
				else
					result << g
				end
			end
		end

		result
	end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy, :duplicate]

  before_action :authenticate_user!

  # GET /gigs
  # GET /gigs.json
  def index
    count_next_years = 0
    Gig.all.each do |gig|
      count_next_years += gig.ensure_next_year
    end
    if count_next_years > 0
      flash.now[:notice] = "#{count_next_years} Gigs für nächstes Jahr angelegt, weil sie dieses Jahr vorbei sind."
    end




    if params[:archived]
      @gigs = Gig.all.order(:datetime)
    else
      @gigs = []

      Gig.where("datetime >= :date", :date => 1.week.ago).order(:datetime).each do |gig|
        if gig.current_status != "archiviert"
          @gigs << gig
        end
      end
    end

    @count_statuses = Hash.new
    @different = Hash.new

    @gigs.each do |gig|
      @different[gig.location.name] = "ok"

      @count_statuses[gig.current_status] ? @count_statuses[gig.current_status] += 1 : @count_statuses[gig.current_status] = 1
    end

    @status_values = StatusValue.all
    @members = current_user.band.user
    @locations = Location.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new

    set_contact_and_location
  end

  # GET /gigs/1/edit
  def edit
    set_contact_and_location

    @contacts = Contact.all.map { |e| e.summary }
    @contacts = [@contacts, ""].flatten!

    @locations = Location.all.map { |e| e.name }
    @no_edit_for_contact_and_location = true

    @mails = @gig.email.order(:transferred_at).reverse
    @reminders = @gig.reminder

    @statuses = @gig.status
  end

  def duplicate
    new_gig = @gig.duplicate_for_next_year
    redirect_to edit_gig_path(new_gig), notice: "Der Gig wurde dupliziert!"
  end

  # POST /gigs
  # POST /gigs.json
  def create
    gig_params = set_attributes

    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save

        Status.create(gig_id: @gig.id, status_value_id: StatusValue.find_by(text: @status).id)

        format.html { redirect_to edit_gig_path(@gig), notice: I18n.t('models.created') }
        format.json { render :show, status: :created, location: @gig }

        Activity.create(what: "Gig " + (@gig.location ? "#{@gig.location.name} #{@gig.name}" : "#{@gig.name}") + " wurde erstellt",
          url: "/gigs/#{@gig.id}/edit",
          manual: false)
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    gig_params = set_attributes

    Activity.create(what: "Gig " + (@gig.location ? "#{@gig.location.name} #{@gig.name}" : "#{@gig.name}") + " wurde bearbeitet",
      url: "/gigs/#{@gig.id}/edit",
      manual: false)

    respond_to do |format|
      if @gig.update(gig_params)

        if @gig.current_status != @status
          Status.create(gig_id: @gig.id, status_value_id: StatusValue.find_by(text: @status).id)
        end

        format.html { redirect_to edit_gig_path(@gig), notice: I18n.t('models.updated') }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    # in Zukunft lieber archivieren!

    Email.where(gig_id: @gig.id).destroy_all
    Status.where(gig_id: @gig.id).destroy_all

    @gig.destroy


    respond_to do |format|
      format.html { redirect_to gigs_url, notice: I18n.t('models.destroyed') }
      format.json { head :no_content }
    end
  end








  def edit_band
    u = User.find(params[:id])

    u[params[:attribute]] = params[:text]
    u.save

    if u.errors.empty?
      redirect_to "/settings"
    else
      redirect_to "settings", alert: "Beim Speichern der Band hat es Fehler gegeben: #{u.errors.full_messages.join("; ")}"
    end
  end

  def locations
    if params[:festivals]
      @locations = Location.all
    else
      @locations = Location.where(festival: false)
    end
    @contacts = Contact.all.map { |e| e.summary }

    @contacts = [@contacts, ""].flatten!
  end

  def edit_location
    l = Location.find(params[:location_id])

    l[:name] = params[:locationname]
    l[:website] = params[:locationwebsite]
    l[:address] = params[:locationaddress]
    l[:festival] = params[:locationisfestival] == "on"

    cl = Contactlocation.find_by(location_id: l.id)
    
    /(?<name>.*) \((?<email>.*)\)/ =~ params[:locationcontact]
    c = Contact.find_by(name: name, email: email)

    if c
      # das kann nur passieren, wenn noch kein Kontakt eingetragen ist und jetzt immer noch nicht
      if cl
        cl[:contact_id] = c.id
        cl.save
      else
        Contactlocation.create(location_id: l.id, contact_id: c.id)
      end
    else
      # Wenn kein Kontakt gefunden wird, aber schon eine contact-location existiert, dann lösche sie
      if cl
        cl.destroy
        logger.debug "destroyed contactlocation"
      end
    end


    if l.save
      redirect_to request.referer, notice: "Die Location wurde geändert."
    else
      redirect_to request.referer, alert: "Die Location konnte nicht gespeichert werden: #{l.errors.full_messages.join("; ")}"
    end
  end

  def post_locations
    l = Location.create(name: params[:name], address: params[:address], festival: params[:festival], website: params[:website])

    if l.errors.empty?
      redirect_to locations_path, notice: "Die Location wurde gespeichert."
    else
      redirect_to locations_path, alert: "Die Location konnte nicht gespeichert werden: #{l.errors.full_messages.join("; ")}"
    end
  end

  def contacts
    @contacts = Contact.all
  end

  def edit_contact
    c = Contact.find(params[:contact_id])

    c[:name] = params[:contactname]
    c[:email] = params[:contactemail]
    c[:telephone] = params[:contactphone]
    c[:info] = params[:contactinfo]

    if c.save
      redirect_to request.referer, notice: "Der Kontakt wurde gespeichert."
    else
      redirect_to request.referer, alert: "Der Kontakt konnte nicht gespeichert werden: #{c.errors.full_messages.join("; ")}"
    end
  end

  def post_contacts
    c = Contact.create(name: params[:name], email: params[:email], telephone: params[:telephone], info: params[:info])

    if c.errors.empty?
      redirect_to contacts_path, notice: "Der Kontakt wurde gespeichert."
    else
      redirect_to contacts_path, alert: "Der Kontakt konnte nicht gespeichert werden: #{c.errors.full_messages.join("; ")}"
    end
  end

  def create_reminder
    r = Reminder.create(text: params[:text], due: params[:due], done: false, gig_id: params[:gig_id])

    if r.errors.empty?
      redirect_to request.referer, notice: "Die Erinnerung wurde gespeichert."
    else
      redirect_to request.referer, alert: "Die Erinnerung konnte nicht gespeichert werden: #{r.errors.full_messages.join("; ")}"
    end
  end

  def settings
    @status_values = StatusValue.all
    t = Email.get_template

    @template_subject = t.subject
    @template_text = t.text

    fnt = Email.get_template_fan_news
    @fan_news_subject = fnt.subject
    @fan_news_text = fnt.text

    @members = current_user.band.user
  end

  def edit_status
    sv = StatusValue.find(params[:status_id])

    sv[:text] = params[:statustext]
    sv[:order] = params[:statusorder]

    if sv.save
      redirect_to settings_path, notice: "Der Statuswert wurde gespeichert."
    else
      redirect_to settings_path, alert: "Der Statuswert konnte nicht gespeichert werden: #{sv.errors.full_messages.join("; ")}"
    end
  end

  def post_settings
    sv = StatusValue.create(text: params[:text], order: params[:order])

    if sv.errors.empty?
      redirect_to settings_path, notice: "Der Statuswert wurde hinzugefügt."
    else
      redirect_to settings_path, alert: "Der Statuswert konnte nicht gespeichert werden: #{sv.errors.full_messages.join("; ")}"
    end
  end

  def edit_template
    if params[:template] == "template"
      mail = Email.get_template
    elsif params[:template] == "template_fan_news"
      mail = Email.get_template_fan_news
    end

    mail[:subject] = params[:subject]
    mail[:text] = params[:text]

    if mail.save
      redirect_to settings_path, notice: "Die E-Mail-Vorlage wurde geändert."
    else
      redirect_to settings_path, alert: "Die E-Mail-Vorlage konnte nicht geändert werden: #{mail.errors.full_messages.join("; ")}"
    end
  end

  def apply
    @relevant_gigs = []

    Gig.all_that_need_to_be_checked.each do |g|
      if g.datetime < DateTime.now + Rails.configuration.months_until_application.month
        @relevant_gigs.push(g)
      end
    end

    @relevant_gigs = @relevant_gigs.sort_by { |x| x.datetime }
  end

  def post_jump
    # find search
    found = Gig.joins(:location).where("locations.name LIKE ? or gigs.name LIKE ?", "%#{params[:name]}%", "%#{params[:name]}%").first

    if found
      redirect_to edit_gig_path(found), notice: "#{found.location.name} gefunden!"
    else
      redirect_to gigs_path, alert: "Unter diesem Namen konnte nichts gefunden werden ..."
    end
  end

  def post_apply
    count = 0

    Gig.all_that_need_to_be_sent.each do |g|
      mail = g.get_apply_email

      GigMailer.apply_contact(mail, g.contact.email).deliver
      mail.email_type_id = EmailType.find_by(text: "apply_sent").id
      mail.transferred_at = DateTime.now
      mail.save
      count += 1
    end

    Activity.create(what: "#{count} E-Mails wurden versendet.",
          manual: false)

    redirect_to gigs_path, notice: "#{count} E-Mails wurden versendet."
  end

  def show_mail
    @mail = Email.find_by(gig_id: params[:id], email_type_id: EmailType.find_by(text: "apply_created").id)
    @contact = Gig.find(params[:id]).contact
  end

  def send_single_mail
    mail = Email.find(params[:mail_id].to_i)

app/helpers/gigs_helper.rb
module GigsHelper
	def without_http(s)
		var = s.gsub(/http:\/\//, "")
		var.gsub(/https:\/\//, "")
	end

	def just_domain(s)
		s.gsub(/(.*?)\/.*/,'\1')
	end
end

app/views/gigs/_email_bearbeiten_popup.html.erb
<!-- Modal -->
<div id="emailBearbeitenPopup" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">E-Mail / Nachricht bearbeiten</h4>
      </div>

      <%= form_tag "/edit_mail" do %>
        <div class="modal-body">
          <div class="form-group row">
            <%= hidden_field_tag :gig_id, "", value: @gig.id %>
            <%= hidden_field_tag :email_type_id, "", value: EmailType.find_by(text: "manually_entered").id %>
            <%= hidden_field_tag :email_id, "", id: "e_id" %>

            <div class="col-md-6">
              <%= label_tag :subject, "Betreff (inkl. Kanal, wenn nicht E-Mail)" %><br />
              <%= text_field_tag :subject, nil, class: "form-control", id: "e_subject" %>
            </div>

            <div class="col-md-6">
              <%= label_tag :transferred_at, "Übertragen am" %><br />
              <%= text_field_tag :transferred_at, nil, placeholder: "JJJJ-MM-TT", class: "form-control", id: "e_transferred_at" %>
            </div>
            
            <div class="col-md-12">
              <%= label_tag :text, "Text" %><br />
              <%= text_area_tag :text, nil, cols: "30", rows: "10", class: "form-control", id: "e_text" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag type: "submit", class: "btn btn-primary" do %>
            Speichern
          <% end %>
        </div>
      <% end %>
     
    </div>

  </div>
</div>

app/views/gigs/_reminder_erstellen_popup.html.erb
<!-- Modal -->
<div id="reminderErstellenPopup" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Erinnerung erstellen</h4>
      </div>

      <%= form_tag "/gigs/create_reminder" do %>
        <div class="modal-body">
          <div class="form-group row">
            <%= hidden_field_tag :gig_id, "", value: @gig.id %>

            <div class="col-md-6">
              <%= label_tag :due, "Fällig" %><br />
              <%= text_field_tag :due, nil, placeholder: "JJJJ-MM-TT", class: "form-control" %>
            </div>
            
            <div class="col-md-12">
              <%= label_tag :text, "Text" %><br />
              <%= text_area_tag :text, @template_text, cols: "30", rows: "10", class: "form-control" %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag type: "submit", class: "btn btn-primary" do %>
            Speichern
          <% end %>
        </div>
      <% end %>
     
    </div>

  </div>
</div>

app/views/gigs/activities.html.erb
<% title "Aktivitäten" %>


<h1><i class="glyphicon glyphicon-flash"></i> Aktivitaeten</h1>

<%= form_tag "/activities" do %>
<div class="form-inline">
    <%= text_field_tag :what, nil, class: "form-control", placeholder: "Was", size: 80 %>
    <%= text_field_tag :url, nil, class: "form-control", placeholder: "URL (optional)" %>
    <%= button_tag "Hinzufügen", type: "submit", class: "btn btn-primary" %>
</div>
<% end %>

<br>
<br>

<p>Die Einträge werden für gewöhnlich automatisch erstellt. <span style="background-color:rgb(200,200,255);">Manuelle Einträge sind so gekennzeichnet.</span></p>
<p>Bisher wird erfasst ob:</p>
<ul>
  <li>Gigs erstellt / geändert wurden</li>
  <li>E-Mails versendet wurden (mehrere oder einzeln)</li>
  <li>Nachrichten zu Gigs gespeichert wurden</li>
</ul>


<div class="table-responsive">
<table class="table table-striped">
<thead>
  <tr>
    <th>Erstellt</th>
    <th>Was</th>
    <th>Link</th>
    <th colspan="2"></th>
  </tr>
</thead>

<tbody>
  <% @activities.each do |a| %>
    <tr class="<%= a.manual ? "manual" : "" %>">
      <td><%= "#{readable_datetime(a.created_at)} (#{Rails.datetime_relative(a.created_at)})" %></td>
      <td><%= a.what %></td>
      <td><%= link_to "(hier)", a.url if a.url and not a.url.blank? %></td>
<!--
      <td align="center" title="bearbeiten">
        <%# link_to edit_gig_path(gig) do %>
          <div style="height:100%;width:100%">
            <i class="glyphicon glyphicon-edit"></i>
          </div>
        <%# end %>
      </td>
      <td align="center" title="kopieren">
        <%# link_to duplicate_gig_path(gig) do %>
          <div style="height:100%;width:100%">
            <i class="glyphicon glyphicon-duplicate"></i>
          </div>
        <%# end %>
      </td>
      -->
    </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/gigs/apply.html.erb
<% title "Dringende Maßnahmen" %>


<h1 style="color:red"><i class="glyphicon glyphicon-fire"></i> Dringende Maßnahmen</h1>

<div class="div-block">
<h2>Bewerbung erforderlich</h2>

<p>Es werden nur die Gigs der nächsten <%= Rails.configuration.months_until_application %> Monate betrachtet, bei denen eine Aktion dringend nötig ist.</p>

<% if @relevant_gigs.empty? %>
  <strong>Gerade ist nichts zu tun 😊</strong>
<% else %>
  <div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>(voraussichtliche) Stagetime</th>
      <th>Info</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @relevant_gigs.each do |g| %>
      <tr>
        <td><%= link_to g.short_text, edit_gig_path(g.id) %></td>
        <td><%= Rails.date_relative(g.datetime.to_date) %></td>
        <td><%= g.contact.info %></td>
        <td class="<%= g.current_status %>"><%= g.current_status %></td>
        <td><%= link_to "ansehen", show_mail_url(g.id) %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>

<% end %>
</div>

app/views/gigs/index.html.erb
<% title "Gigs / Festivals" %>

<h1><i class="glyphicon glyphicon-star"></i> Gigs / Festivals</h1>
<%= link_to "Neu", new_gig_path, class: "btn btn-default" %>
<% if params[:archived] %>
  <%= link_to "archivierte und vergangene Gigs verstecken", gigs_path, class: "btn btn-default" %>
<% else %>
  <%= link_to "archivierte und vergangene Gigs anzeigen", gigs_path(archived: true), class: "btn btn-default" %>
<% end %>
<br />
<br />

<p>Ganz rechts in jeder Zeile kann ein Gig kopiert werden. Er wird dann automatisch ins nächste Jahr kopiert. Ein Gig von 2017 würde dann also zu 2018 kopiert werden.</p>


<p>
  <% @count_statuses.each do |k,v| %>
    <%= raw("<span class='#{k} count'>#{v} #{k}</span> ") %>
  <% end %>
  <%= raw("<span class='count'>#{@different.size} verschiedene Locations</span> ") %>
  <%= raw("<span class='count'>#{@gigs.size} Zeilen</span> ") %>
</p>

<div class="table-responsive">
<table class="table table-striped">
<thead>
  <tr>
    <th>Name / Location</th>
    <th>Adresse</th>
    <th>Stagetime</th>
    <th>Status</th>
    <th>(Anzahl) Letzte Aktion</th>
  </tr>
</thead>

<tbody>
  <% @gigs.each do |gig| %>

    <%
    tr_class = "" 

    if gig.archived
      tr_class = "archived"
    elsif gig.datetime < 1.week.ago
      tr_class = "old"
    elsif gig.datetime < 0.week.ago
      tr_class = "recent"
    end
    %>

    <tr class="<%= tr_class %>">
      <td>
        <%= link_to(edit_gig_path(gig), target: "_blank") do %>
          <%= "#{gig.short_text}" %>
        <% end %>
      </td>

      <td>
        <%= link_to raw(gig.short_location), "https://www.google.de/maps?q=from:+w%C3%BCrzburg+to:+#{gig.short_location}", target: "_blank" %>

      </td>

      <td>
        <%= link_to(map_path(relative: gig.datetime.strftime("%Y-%m-%d")), target: "_blank") do %>
          <%= gig.datetime.strftime("%d.%m.%Y") %>    
        <% end %>
      </td>

      <td class="<%= gig.current_status %>"><%= gig.current_status %></td>
      <td style="<%= gig.last_action_style %>"><%= "(#{gig.action_count}) #{gig.last_action}" %></td>
    </tr>
  <% end %>
</tbody>
</table>
</div>

app/views/gigs/show_band.html.erb
<h1><%= current_user.band.name %></h1>



<div class="table-responsive">
<table class="table table-striped">
<thead>
  <tr>
    <th>Mitglied</th>
    <th>Instrumente</th>
  </tr>
</thead>

<tbody>
  <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.instruments %></td>
      </tr>
    <% end %>
</tbody>
</table>
</div>

<br>

<%= link_to I18n.t('models.new'), new_gig_path, class: "btn btn-default" %>

app/views/gigs/show_mail.html.erb
<% title "Nachricht anzeigen" %>

<h1>Bewerbungsmail an ...</h1>
<p><%= @contact.summary %></p>

<%= link_to "Zurück zur Liste", dringende_massnahmen_path, class: "btn btn-default" %>
<br>
<br>

<p><strong>Betreff:</strong> <%= @mail.subject %></p>
<p class="email_type"><strong>Typ:</strong> <%= EmailType.find(@mail.email_type_id).text %></p>
<p><%= raw(nl2br(@mail.text)) %></p>

<% if @contact.email and not @contact.email.empty? %>
	<%= link_to "So versenden", send_single_mail_url(mail_id: @mail.id, contact_id: @contact.id), class: "btn btn-primary" %>
<% end %>
<br>
<br>
<%= link_to "Diese Vorlage neu erstellen", recreate_mail_url(@mail.id), class: "btn btn-danger" %>





<%# später ... %>
<%# render "email_bearbeiten_popup" %>