config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => :registrations
  resources :gigs, except: [:show] do
    member do
      get 'duplicate'
    end
  end
  
  post 'band/edit' => 'gigs#edit_band'

  get 'settings' => 'gigs#settings'
  post 'settings' => 'gigs#post_settings'
  post 'settings/edit_status' => 'gigs#edit_status'
  post 'settings/edit_template' => 'gigs#edit_template'

  match 'dringende_massnahmen' => 'gigs#apply', :as => :dringende_massnahmen, :via => :get
  post 'apply' => 'gigs#post_apply'
  post 'jump' => 'gigs#post_jump'
  get 'show_mail/:id' => 'gigs#show_mail', as: "show_mail"
  get 'recreate_mail/:id' => 'gigs#recreate_mail', as: "recreate_mail"
  get 'remove_mail/:id' => 'gigs#remove_mail', as: "remove_mail"
  post 'edit_mail' => 'gigs#edit_mail', as: "edit_mail"
  get 'send_single_mail' => 'gigs#send_single_mail', as: "send_single_mail"

  post 'gigs/create_reminder'
  post 'gigs/create_email'

  get 'locations' => 'gigs#locations'
  post 'locations' => 'gigs#post_locations'
  post 'gigs/edit_location' => 'gigs#edit_location'
  get 'contacts' => 'gigs#contacts'
  post 'contacts' => 'gigs#post_contacts'
  post 'gigs/edit_contact' => 'gigs#edit_contact'

  
  get 'map' => 'gigs#map'

  get 'activities' => 'gigs#activities'
  post 'activities' => 'gigs#post_activities'

  root 'gigs#index'

end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "/", class: "navbar-brand page-scroll" do %>
        <span class="anda"><%= Rails.configuration.bandname %> - GigHunter</span>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li<%= is_active?("gigs#apply") ? raw(" class='active'") : "" %>>
            <%= link_to dringende_massnahmen_path do %>
              <i class="glyphicon glyphicon-fire"></i> Dringend
            <% end %>
          </li>
          <li<%= is_active?("gigs#new") ? raw(" class='active'") : "" %>>
            <%= link_to new_gig_path do %>    
              <i class="glyphicon glyphicon-plus"></i> Neu
            <% end %>  
          </li>
          <li<%= is_active?("gigs#index|edit") ? raw(" class='active'") : "" %>>
            <%= link_to gigs_path do %>    
              <i class="glyphicon glyphicon-star"></i> Gigs
            <% end %>  
          </li>
          <li<%= is_active?("gigs#map") ? raw(" class='active'") : "" %>>
            <%= link_to map_path do %>    
              <i class="glyphicon glyphicon-map-marker"></i> Karte
            <% end %>
          </li>
          <!--li<%# is_active?("gigs#contacts") ? raw(" class='active'") : "" %>>
            <%# link_to contacts_path do %>  
              <i class="glyphicon glyphicon-user"></i> Kontakte
            <%# end %>
          </li-->
          <!--l<li<%# is_active?("gigs#fans") ? raw(" class='active'") : "" %>>
            <%# link_to fans_path do %>  
              <i class="glyphicon glyphicon-heart"></i> Fans
            <%# end %>
          </li-->
          <li<%= is_active?("gigs#activities") ? raw(" class='active'") : "" %>>
            <%= link_to activities_path do %>
              <i class="glyphicon glyphicon-flash"></i> Aktivitäten
            <% end %>
          </li>
          <li<%= is_active?("gigs#settings") ? raw(" class='active'") : "" %>>
            <%= link_to "/settings" do %>
              <i class="glyphicon glyphicon-cog"></i> Einstellungen
            <% end %>
          </li>
          <li>
            <%= form_tag "/jump", class: "form-inline" do %>
              <%= text_field_tag :name, nil, class: "form-control", placeholder: "z.B. Wacken" %>
              <%= button_tag "Suchen", type: "submit", class: "btn-sm btn-primary" %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div style="float:right">
    <% if user_signed_in? %>
      <%= I18n.t 'devise.info.logged_in_as' %> <strong><%= current_user.email %></strong>.
      <% if false %>
        <%= link_to I18n.t('devise.info.edit_profile'), edit_user_registration_path, :class => 'navbar-link' %> |
      <% end %>
      <%= link_to I18n.t('devise.info.logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <% if false %>
        <%= link_to I18n.t('devise.info.sign_up'), new_user_registration_path, :class => 'navbar-link'  %> |
      <% end %>
      <%= link_to I18n.t('devise.info.login'), new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : 'Gig Organisation und Überblick' %> - GigHunter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- Mobile Specific Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">

	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<%= yield %>

	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>

</div>

<div class="footer">
	<p><em>GigHunter ist ein Werkzeug für Bands, mit dem sie sich einen Überblick über ihre Kontakte zu Veranstaltern und den aktuellen Stand der Organisation von Auftritten verschaffen können.</em></p>
</div>




</body>
</html>